try{    
//code that may throw an exception    
}catch(Exception_class_Name ref){}